### ISSUE TITLE
Connection issue shuttleCP to SPJS

### ISSUE THREAD

**Issue by njkeng** [lordmundi/shuttleCP#6]
Hi,
I have SPJS running on a RasPi2.  No issues with ChiliPeppr and SPJS on my Pi.  I followed the directions to install shuttleCP and its' dependencies.  ShuttleCP connects but it takes about 10 seconds to do so.  After it connects, whenever I send a command, it fails, drops the connection and takes about 10 seconds to re-connect.  And on it goes.  Example output from the shuttle script is as follows:

--START OF OUTPUT--

pi@raspberrypi ~/shuttleCP $ sudo ./shuttlecp /dev/input/by-id/usb-Contour_Design_ShuttleXpress-event-if00
Attempting connection to localhost:8989
--10 SECOND PAUSE HERE--
Websocket connected.
Shuttle device connected.
broadcast {"id":"shuttlexpress", "action":"a"}
Sending websocket cmd: broadcast {"id":"shuttlexpress", "action":"a"}

ERROR: Only sent 0 bytes of command: broadcast {"id":"shuttlexpress", "action":"a"}

Sent 0 commands
============ Reinitializing connections
Attempting connection to localhost:8989
--10 SECOND PAUSE HERE--
Websocket connected.
Shuttle device connected.
Sending websocket cmd: send /dev/ttyACM0 G91 G0 A1.000
G90

ERROR: Only sent 0 bytes of command: send /dev/ttyACM0 G91 G0 A1.000
G90

Sending websocket cmd: send /dev/ttyACM0 G91 G0 A1.000
G90

ERROR: Only sent 0 bytes of command: send /dev/ttyACM0 G91 G0 A1.000
G90

Sent 0 commands
============ Reinitializing connections
Attempting connection to localhost:8989
--10 SECOND PAUSE HERE--
Websocket connected.
Shuttle device connected.

-- END OF OUTPUT--

I have tried three different versions of nopoll:
nopoll-0.2.7.b164
nopoll-0.2.9.b207
nopoll-0.3.1.b217
All three versions exhibit the same behavior.

Any ideas?  Are there any log files anywhere that could give more info?

Nathan.

**Comment by lordmundi** [comment]
well, i'm not sure what that 10 second pause is.  That seems odd.
1. Is SPJS running on the same machine as ShuttleCP?  If not, make sure you
   set the host at the top of shuttlecp.c.
2. Before you run shuttleCP, have you went to Chilipeppr and connected to
   SPJS and opened the connection to your board?  Be sure and do that first.
3. Is is possible something else is running on port 8989?  Perhaps it is
   connecting to some other server.
4. Can you examine the verbose output of SPJS? Does it confirm it is
   running on 8989?
5. nopoll 0.2.7.b164 should work as that is what I am using.
6. Could some sort of firewall or iptables be running on the pi that is
   interfering with the connection?

FG

**Comment by njkeng** [comment]
OK.  I couldn't identify any issues with ports, firewalls or iptables, but I knew my installation of Raspbian wasn't clean.  I had been using the SD for another application.  So, I went with a clean install of Raspbian and viola!  Clean connections to port 8989.

Next, shuttleCP was sending commands, but no movement on the CNC.  I noticed shuttleCP was sending to /dev/ttyACM0.  I checked, and I didn't have one of those.  I had a look at the port ChiliPeppr was using.  It was opening /dev/ttyUSB0.  I modified shuttlecp.c to use /dev/ttyUSB0 then re-ran make.  Magic!  Everything works great now.

Thanks very much for your efforts with this code.  Well done.

Just one small suggestion if I may.  Can you please make the serial port a command line option?

Thanks again!

Nathan.

**Comment by lordmundi** [comment]
Yeah, there is already an issue open for that. Feel free to add it in and
send me a pull request. If not, I'll get around to it one day.

Glad you got it working.

FG
